config/routes.rb
Rails.application.routes.draw do
  resources :stimulus, only: [:index] do
    collection do
      get :clock
      get :nested_form
    end
  end

  root 'stimulus#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/stimulus_controller.rb
class StimulusController < ApplicationController
  def index
  end

  def nested_form
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StimulusSandboxRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stimulus/_asynchronously_loading_html.html.erb
<div data-controller="content-loader"
     data-content-loader-url="<%= clock_stimulus_path %>"
     data-content-loader-refresh-interval="5000"
     >
</div>

app/views/stimulus/clock.html.haml
= Time.current

app/views/stimulus/index.html.haml
%div
  %h5 Hello Stimulus
  = render 'hello'

%div
  %h5 Building Something Real
  = render 'building_something_real'

%div
  %h5 Building a Slideshow - 1
  = render 'building_slide_show'

%div
  %h5 Building a Slideshow - 2
  = render 'building_slide_show'

%div
  %h5 Asynchronously Loading HTML
  = render 'asynchronously_loading_html'

app/views/stimulus/nested_form.html.haml
%div{ data: { controller: 'nested-form' } }
  %h5{ data: { target: 'nested-form.title' } }
  %div
    %h6
      total:
      %span{ data: { target: 'nested-form.total' } }
  %div
    .hide{ data: { target: 'nested-form.template' } }
      %li{ data: { target: 'nested-form.item' } }
        %input{ type: 'number', value: 0, name: 'items[][number]', data: { action: 'change->nested-form#render' } }
        %button{ data: { action: 'click->nested-form#remove' } } Remove
    %ul{ data: { target: 'nested-form.itemContainer' } }
    %button{ data: { action: 'nested-form#add' } } Add